version: '3'

services:

  back:
    build: ./backend
    stdin_open: true
    tty: true
    ports:
      - "5000:5000"
    environment:
      - DB-HOST=db
      - API-KEY=AIzaSyCJ-vBZePh6EmsJQ7IeTyizy0dXwtVf79U
      - MQ-HOST=mq
    networks:
      net1:

  db:
    build: ./database
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=appdb
      - POSTGRES_DB=appdb
    networks:
      net1:
  front:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - BACK_HOSTNAME=localhost
    networks:
      net1:
  msg:
    build: ./messaging
    stdin_open: true
    tty: true
    environment:
      - GMAIL-USER=truenorth.deliveryconfirm@gmail.com
      - GMAIL-PASS=0okmju7ygvfr4
      - MQ-HOST=mq
      - SMS-HOST=sms
    networks:
      net1:
  mq:
    image: rabbitmq
    ports:
      - "5672:5672"
    networks:
      net1:
  sms:
    build: ./sms
    stdin_open: true
    tty: true
    ports:
      - "5001:5001"
    volumes:
      - ./sms/sms_log:/data
    networks:
      net1:

networks:
  net1:
